# Change these first
owner: acoffman # Your GitHub organization or username, where this repository lives
repo: civic-status # The name of this repository

sites:
  - name: CIViC Site
    url: https://civicdb.org
  - name: CIViC Docs
    url: https://docs.civicdb.org
  - name: CIViC API
    url: https://civicdb.org/api/graphiql

status-website:
  cname: status.adamcoffman.dev
  logoUrl: https://raw.githubusercontent.com/griffithlab/civic-v2/main/client/src/assets/images/civic-logo_sidebar-expanded.png
  name: CIViC
  introMessage: Please feel free to contact us at [help@civicdb.org](mailto:help@civicdb.org) with any questions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: CIViC
      href: https://civicdb.org
assignees:
  - acoffman
